x-logging-syslog: &logging
  driver: syslog
  options:
    syslog-address: "${SYSLOG_ADDRESS}"
    tag: "${SYSLOG_TAG:-bgpm}"
    syslog-format: "${SYSLOG_FORMAT:-rfc5424}"

services:
  bird:
    build: ./bird
    container_name: ${PROJECT_NAME:-bgpm}-bird
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    env_file:
      - .env
    environment:
      # Core settings
      - LOCAL_AS=${LOCAL_AS}
      - ROUTER_ID=${ROUTER_ID}
      - PEER_COUNT=${PEER_COUNT}

      # Optional tuning
      - BIRD_LOG_LEVEL=${BIRD_LOG_LEVEL:-info}
      - BIRD_GR_TIMER=${BIRD_GR_TIMER:-240}
      - BIRD_SCAN_TIME=${BIRD_SCAN_TIME:-15}

    volumes:
      - ./bird/config:/etc/bird
    logging: *logging
    healthcheck:
      test: ["CMD-SHELL", "birdc show status | grep -q 'BIRD'"]
      interval: 30s
      timeout: 5s
      retries: 5

  syslog:
    profiles: ["local-syslog"]
    build: ./syslog-ng
    container_name: ${PROJECT_NAME:-bgpm}-syslog
    restart: unless-stopped
    ports:
      - "8514:8514/tcp"
      - "8514:8514/udp"
    volumes:
      - ./syslog-ng/data:/var/log/syslog
